#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ids-lab
    username: ubuntu
    password: "__PASSWORD_HASH__"
  ssh:
    install-server: true
    authorized-keys:
      - __SSH_PUB_KEY__
  network:
    version: 2
    ethernets:
      enp0s3:
        dhcp4: false
        addresses: [192.168.56.101/24]
        gateway4: 192.168.56.1
        nameservers:
          addresses: [8.8.8.8,8.8.4.4]
  storage:
    layout:
      name: direct
  packages:
    - curl
    - git
  late-commands:
    - curtin in-target --target=/target -- curl -sfL https://get.k3s.io | sh -
    - curtin in-target --target=/target -- systemctl enable k3s
